"""Reference learning agents."""

from infinite_rulebook.agents.comparison import (
    ExpandingTargetSchedule,
    FactorizedQueryAgent,
    FixedTargetPolicy,
    NoveltyDirectedPolicy,
    RelevantInformationDirectedPolicy,
    RewardDirectedPolicy,
    ScheduledTargetPolicy,
    TotalInformationDirectedPolicy,
    distractor_targets,
    useful_targets,
)
from infinite_rulebook.agents.integration import (
    P1RoundTrace,
    exact_ind_bit_equivalent,
    execute_p1_round,
    factorized_information_ledger,
    population_information_estimate,
    symbolic_query_to_target,
    target_to_symbolic_query,
)
from infinite_rulebook.agents.protocols import (
    AcquisitionContext,
    AgentCheckpoint,
    CapabilityManifest,
    ObservationBatch,
    QueryAction,
    QueryTarget,
    SymbolicAgent,
    TargetKey,
)
from infinite_rulebook.agents.sanity import (
    FreshCoordinateSanityAgent,
    average_bit_equivalent,
    average_bit_equivalent_slope,
    bit_equivalent_slope,
    expected_coordinate_reward,
    expected_reward_slope,
)

__all__ = [
    "AcquisitionContext",
    "AgentCheckpoint",
    "CapabilityManifest",
    "ExpandingTargetSchedule",
    "FactorizedQueryAgent",
    "FixedTargetPolicy",
    "FreshCoordinateSanityAgent",
    "NoveltyDirectedPolicy",
    "ObservationBatch",
    "P1RoundTrace",
    "QueryAction",
    "QueryTarget",
    "RelevantInformationDirectedPolicy",
    "RewardDirectedPolicy",
    "ScheduledTargetPolicy",
    "SymbolicAgent",
    "TargetKey",
    "TotalInformationDirectedPolicy",
    "average_bit_equivalent",
    "average_bit_equivalent_slope",
    "bit_equivalent_slope",
    "distractor_targets",
    "exact_ind_bit_equivalent",
    "execute_p1_round",
    "expected_coordinate_reward",
    "expected_reward_slope",
    "factorized_information_ledger",
    "population_information_estimate",
    "symbolic_query_to_target",
    "target_to_symbolic_query",
    "useful_targets",
]
