"""Versioned, preregistered study protocols."""

from infinite_rulebook.studies.symbolic_construct import (
    MINIMUM_EQUIVALENCE_POWER,
    POWER_CANDIDATE_ENVIRONMENTS,
    POWER_SIMULATION_ERROR_ALPHA,
    PRIMARY_MINIMUM_EFFECTS,
    S5_BOOTSTRAP_DIAGNOSTIC_LOCATION,
    SYMBOLIC_V1_DESIGN_HASH,
    build_symbolic_analysis_plan,
    build_symbolic_canary_plan,
    calibration_evidence_hash,
    expected_analysis_groups,
    expected_confirmatory_margins,
    expected_confirmatory_registration,
    expected_confirmatory_tolerances,
    power_equivalence_hypotheses,
    power_hypotheses,
    symbolic_v1_design_hash,
    symbolic_v1_design_payload,
    verify_symbolic_calibration_design,
    verify_symbolic_confirmatory_contract,
)

__all__ = [
    "MINIMUM_EQUIVALENCE_POWER",
    "POWER_CANDIDATE_ENVIRONMENTS",
    "POWER_SIMULATION_ERROR_ALPHA",
    "PRIMARY_MINIMUM_EFFECTS",
    "S5_BOOTSTRAP_DIAGNOSTIC_LOCATION",
    "SYMBOLIC_V1_DESIGN_HASH",
    "build_symbolic_analysis_plan",
    "build_symbolic_canary_plan",
    "calibration_evidence_hash",
    "expected_analysis_groups",
    "expected_confirmatory_margins",
    "expected_confirmatory_registration",
    "expected_confirmatory_tolerances",
    "power_equivalence_hypotheses",
    "power_hypotheses",
    "symbolic_v1_design_hash",
    "symbolic_v1_design_payload",
    "verify_symbolic_calibration_design",
    "verify_symbolic_confirmatory_contract",
]
